### ISSUE TITLE
Dockerized Runbot: IOError

### ISSUE THREAD

**Issue by lasley** [OCA/runbot-addons#113]
Hah here's another one for us @moylop260 - 

`IOError: [Errno 2] No such file or directory: '/openerp/addons/.coveralls.yml'`

Examples:
* http://runbot.odoo-community.org/runbot/build/3274053 (https://github.com/OCA/partner-contact/pull/347#issuecomment-264319753)
* https://runbot.odoo-community.org/runbot/build/3273235 (current website/10.0)

```
======== Testing test_server.py ========
command:  /entrypoint_image
 * Starting OpenBSD Secure Shell server sshd       [80G 
[74G[ OK ]
 * Starting PostgreSQL 9.3 database server       [80G 
[74G[ OK ]
Waiting to start psql service...
...psql service started.
Traceback (most recent call last):
  File "/entrypoint_image", line 134, in <module>
    docker_entrypoint()
  File "/entrypoint_image", line 126, in docker_entrypoint
    open(fname_coveralls, 'w').writelines(coveralls_lines)
IOError: [Errno 2] No such file or directory: '/openerp/addons/.coveralls.yml'
Working in /openerp/addons
Using repo odoo/odoo and addons path /openerp/addons,/root/odoo-9.0/addons
WARNING!
Nothing to test- exiting early.

+=======================================
|  Tests summary:
|---------------------------------------
| test_server.py              [1;32mSuccess[0;m
+=======================================
```

**Comment by moylop260** [comment]
This is duplicated with https://github.com/OCA/runbot-addons/issues/111 but with a different message: `failed to create symbolic link /openerp/addons/server_environment_files: No such file or directory` is similar to `IOError: [Errno 2] No such file or directory: '/openerp/addons/.coveralls.yml'`
Docker is using `export HOME=/openerp/addons` instead of `HOME=/root` then all files referenced with `$HOME/something` is failing because is not find it.

**Comment by lasley** [comment]
Ahh sweet thanks @moylop260 - I had a feeling it may be related, but it was a different message so I figured it would be better to create the possible dup instead of possibly expand scope 👍
