### ISSUE TITLE
runbot_build_instructions: modules required for custom builds?

### ISSUE THREAD

**Issue by gurneyalex** [OCA/runbot-addons#30]
I would like to use runbot_build_instructions in the OCA runbot to test server-tools (which needs adding a symlink for the tests to run properly, as is done in the travis config).

However, the runbot.repo view defined in this addon makes the `modules` field mandatory for custom build. Reading the code does not reveal anything obvious for the mandatory character of the field. Am I missing something or can this be changed back safely?

**Comment by gurneyalex** [comment]
@bwrsandman your opinion on this would be greatly appreciated.

**Comment by bwrsandman** [comment]
Custom build module is for supporting things such as the anybox recipe.

The default build just installs all modules it can find unless something is in the modules field.

In the case of a custom build, it is impossible for runbot to know what module you want to install, that's why the module list is mandatory.
